version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=flowise
      - POSTGRES_PASSWORD=flowise
      - POSTGRES_DB=flowise
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  trino-coordinator:
    image: "trinodb/trino:latest"
    ports:
      - '8080:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
    depends_on:
      - trino-worker
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G

  trino-worker:
    image: "trinodb/trino:latest"
    volumes:
      - ./trino/worker/etc:/etc/trino:ro
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 6G

  flowise:
    build: ./flowise
    ports:
      - "3000:3000"
    depends_on:
      - trino-coordinator
    environment:
      LOG_LEVEL: debug
    command: /bin/sh -c "sleep 3; flowise start"

#  autogen:
#    build: ./autogen
  trino-ai-assistant:
    build: ./trino-ai-assistant
    environment:
      openai_api_key: your openai key
    ports:
      - "9080:9080"
      - "7080:7080"

volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local
