server:
  port: 9080
  servlet:
    context-path: /trino

logging:
  level:
    root: debug

trino:
  url: jdbc:trino://trino-coordinator:8080
  filter:
    catalogs:
      - system
    schemas:
      - information_schema